language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- grunt
deploy:
  api_key:
    provider: heroku
    secure: E7M+Hr43y46yMmBV2vKZFowPbb5vnhZTj4MFWUApxRDgwBM42m3ySbbe7ooDbu50CkauxSSyOfAaNZ1er5NtSmUHqi7Dv+MIlqGyJ0+YeISxhxFyM039iIMF0M9k/yiZ3+YIzH3VFw2JE0367+tYIRHROigSnvoOg760GX0U/ck=
    app: debug-gewefope
    strategy: git